SELECT F.ID, N.FISH_NAME, F.LENGTH
FROM FISH_INFO AS F
NATURAL JOIN FISH_NAME_INFO AS N
WHERE F.ID IN (
    SELECT ID
    FROM FISH_INFO
    WHERE (FISH_TYPE, LENGTH) IN (
        SELECT FISH_TYPE, MAX(LENGTH)
        FROM FISH_INFO
        GROUP BY FISH_TYPE
    )
)
ORDER BY F.ID;
